# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wwJYXIcUZ1XRE6-fz3H84E8OrZCzFe4d
"""

!pip install face-recognition

import face_recognition
image = face_recognition.load_image_file("image_data/mat.jpg")
known_image = face_recognition.load_image_file("image_data/mat.jpg")
unknown_image = face_recognition.load_image_file("image_data/mat.jpg")

mat_encoding = face_recognition.face_encodings(known_image)[0]
unknown_encoding = face_recognition.face_encodings(unknown_image)[0]

results = face_recognition.compare_faces([mat_encoding], unknown_encoding)
print(results)

"""## Ce script utilise la camera en temps reel :"""

import face_recognition as fr
import cv2
import numpy as np

video_capture = cv2.VideoCapture(0) # Index (port) de la caméra

face_bank = [] # Initialisation de la banque des têtes

def encode_faces(image_path):
  """
  Cette fonction donne une liste des visages sur une image
  """
 face_locations = face_recognition.face_locations(image_path)
 face_encodings = face_recognition.face_encodings(image_path, face_locations)

 return face_encodings

while True:
  # ¨Process l'image
  ret, frame = video_capture.read()
  small_frame = cv2.resize(frame, (0, 0), fx=0.25, fy=0.25) # Reduit la résolution de l'image
  rgb_small_frame = small_frame[:, :, ::-1] # Convertie le BRG en RGB pour Facial Recognition

  # Encode l'image
  encoded_faces = encode_faces(rgb_small_frame)

  for face in encoded_faces: # Répète les étapes du dessous pour chaque visage
    for face_id in face_bank: # Répète les étapes du dessous pour chaque visage dans la banque

        matches = face_recognition.compare_faces(face_id, face) # Compare les visages
        face_distances = face_recognition.face_distance(face_id, face) # Regarde la ressemblance des visages

        best_match_index = np.argmin(face_distances) # Regarde les visages qui se ressemble

        if matches[best_match_index]: # Le visage est reconnu
          face_bank.remove(face)
          print("face found")

        else: # Le visage n'est pas reconnu
          face_bank.append(face) # Ajout du visage dans la banque
          print("new face detected")

"""## Ce script permet de tester le programme avec des images au lieu d'une camera :"""

import face_recognition as fr
import cv2
import numpy as np

face_bank = [] # Initialisation de la banque des têtes

def encode_faces(image_path):
  """
  Cette fonction donne une liste des visages sur une image
  """
  face_locations = face_recognition.face_locations(image_path)
  face_encodings = face_recognition.face_encodings(image_path, face_locations)

  return face_encodings

while True:
  # Demande l'image
  image = input("Image a utilisé: ")
  if image == "list":
    print(f"Visage Sauvegardé: {face_bank}")
    continue

  image_loaded = face_recognition.load_image_file(image)
  print("Image chargée")

  # ¨Process l'image
  small_frame = cv2.resize(image_loaded, (0, 0), fx=0.25, fy=0.25) # Reduit la résolution de l'image
  print("Image convertie en RGB")

  # Encode l'image
  encoded_faces = encode_faces(small_frame)
  print("Image encodée")

  for face in encoded_faces: # Répète les étapes du dessous pour chaque visage
    print("Itteration de face dans encoded_faces")
    if len(face_bank) == 0:
        face_bank.append(face) # Ajout du visage dans la banque
        print("new face detected")
    else:
        for face_id in face_bank: # Répète les étapes du dessous pour chaque visage dans la banque
            print("Itteration de face_id dans face_bank")

            matches = face_recognition.compare_faces(face_id, face) # Compare les visages
            print("Comparaison des visages")

            face_distances = face_recognition.face_distance(face_id, face) # Regarde la ressemblance des visages
            print("Ressemblance des visages calculé")

            best_match_index = np.argmin(face_distances) # Regarde les visages qui se ressemble
            print("Argmin calculé")

            if matches[best_match_index]: # Le visage est reconnu
              face_bank.remove(face)
              print("face found")

            else: # Le visage n'est pas reconnu
              face_bank.append(face) # Ajout du visage dans la banque
              print("new face detected")

import face_recognition as fr
import cv2
import numpy as np

face_bank = []  # Initialisation de la banque des têtes

def encode_faces(image):
    """
    Cette fonction donne une liste des visages sur une image
    """
    face_locations = fr.face_locations(image)
    face_encodings = fr.face_encodings(image, face_locations)
    return face_encodings

while True:
    image = input("Image à utiliser: ")
    if image == "list":
        print(f"Visages sauvegardés: {len(face_bank)} visage(s)")
        continue

    image_loaded = fr.load_image_file(image)
    print("Image chargée")

    small_frame = cv2.resize(image_loaded, (0, 0), fx=0.25, fy=0.25)
    print("Image réduite")

    encoded_faces = encode_faces(small_frame)
    print(f"{len(encoded_faces)} visage(s) encodé(s)")

    for face in encoded_faces:
        if len(face_bank) == 0:
            face_bank.append(face)
            print("Nouveau visage détecté (banque vide)")
        else:
            # compare la bank
            matches = fr.compare_faces(face_bank, face)
            face_distances = fr.face_distance(face_bank, face)

            if True in matches:
                # trouver les plus proches visages
                best_match_index = np.argmin(face_distances)
                if matches[best_match_index]:
                    print(f"Visage reconnu (index {best_match_index}, "
                          f"distance: {face_distances[best_match_index]:.3f})")
                else:
                    face_bank.append(face)
                    print("Nouveau visage détecté")
            else:
                # Pas de visage detecté
                face_bank.append(face)
                print("Nouveau visage détecté")
